"""Static data for the 66-book Protestant canon, in order."""

CANON: list[dict[str, str | int]] = [
    {"name": "Genesis", "abbreviation": "Gen", "testament": "OT", "chapters": 50},
    {"name": "Exodus", "abbreviation": "Exod", "testament": "OT", "chapters": 40},
    {"name": "Leviticus", "abbreviation": "Lev", "testament": "OT", "chapters": 27},
    {"name": "Numbers", "abbreviation": "Num", "testament": "OT", "chapters": 36},
    {"name": "Deuteronomy", "abbreviation": "Deut", "testament": "OT", "chapters": 34},
    {"name": "Joshua", "abbreviation": "Josh", "testament": "OT", "chapters": 24},
    {"name": "Judges", "abbreviation": "Judg", "testament": "OT", "chapters": 21},
    {"name": "Ruth", "abbreviation": "Ruth", "testament": "OT", "chapters": 4},
    {"name": "1 Samuel", "abbreviation": "1Sam", "testament": "OT", "chapters": 31},
    {"name": "2 Samuel", "abbreviation": "2Sam", "testament": "OT", "chapters": 24},
    {"name": "1 Kings", "abbreviation": "1Kgs", "testament": "OT", "chapters": 22},
    {"name": "2 Kings", "abbreviation": "2Kgs", "testament": "OT", "chapters": 25},
    {"name": "1 Chronicles", "abbreviation": "1Chr", "testament": "OT", "chapters": 29},
    {"name": "2 Chronicles", "abbreviation": "2Chr", "testament": "OT", "chapters": 36},
    {"name": "Ezra", "abbreviation": "Ezra", "testament": "OT", "chapters": 10},
    {"name": "Nehemiah", "abbreviation": "Neh", "testament": "OT", "chapters": 13},
    {"name": "Esther", "abbreviation": "Esth", "testament": "OT", "chapters": 10},
    {"name": "Job", "abbreviation": "Job", "testament": "OT", "chapters": 42},
    {"name": "Psalms", "abbreviation": "Ps", "testament": "OT", "chapters": 150},
    {"name": "Proverbs", "abbreviation": "Prov", "testament": "OT", "chapters": 31},
    {"name": "Ecclesiastes", "abbreviation": "Eccl", "testament": "OT", "chapters": 12},
    {"name": "Song of Solomon", "abbreviation": "Song", "testament": "OT", "chapters": 8},
    {"name": "Isaiah", "abbreviation": "Isa", "testament": "OT", "chapters": 66},
    {"name": "Jeremiah", "abbreviation": "Jer", "testament": "OT", "chapters": 52},
    {"name": "Lamentations", "abbreviation": "Lam", "testament": "OT", "chapters": 5},
    {"name": "Ezekiel", "abbreviation": "Ezek", "testament": "OT", "chapters": 48},
    {"name": "Daniel", "abbreviation": "Dan", "testament": "OT", "chapters": 12},
    {"name": "Hosea", "abbreviation": "Hos", "testament": "OT", "chapters": 14},
    {"name": "Joel", "abbreviation": "Joel", "testament": "OT", "chapters": 3},
    {"name": "Amos", "abbreviation": "Amos", "testament": "OT", "chapters": 9},
    {"name": "Obadiah", "abbreviation": "Obad", "testament": "OT", "chapters": 1},
    {"name": "Jonah", "abbreviation": "Jonah", "testament": "OT", "chapters": 4},
    {"name": "Micah", "abbreviation": "Mic", "testament": "OT", "chapters": 7},
    {"name": "Nahum", "abbreviation": "Nah", "testament": "OT", "chapters": 3},
    {"name": "Habakkuk", "abbreviation": "Hab", "testament": "OT", "chapters": 3},
    {"name": "Zephaniah", "abbreviation": "Zeph", "testament": "OT", "chapters": 3},
    {"name": "Haggai", "abbreviation": "Hag", "testament": "OT", "chapters": 2},
    {"name": "Zechariah", "abbreviation": "Zech", "testament": "OT", "chapters": 14},
    {"name": "Malachi", "abbreviation": "Mal", "testament": "OT", "chapters": 4},
    {"name": "Matthew", "abbreviation": "Matt", "testament": "NT", "chapters": 28},
    {"name": "Mark", "abbreviation": "Mark", "testament": "NT", "chapters": 16},
    {"name": "Luke", "abbreviation": "Luke", "testament": "NT", "chapters": 24},
    {"name": "John", "abbreviation": "John", "testament": "NT", "chapters": 21},
    {"name": "Acts", "abbreviation": "Acts", "testament": "NT", "chapters": 28},
    {"name": "Romans", "abbreviation": "Rom", "testament": "NT", "chapters": 16},
    {"name": "1 Corinthians", "abbreviation": "1Cor", "testament": "NT", "chapters": 16},
    {"name": "2 Corinthians", "abbreviation": "2Cor", "testament": "NT", "chapters": 13},
    {"name": "Galatians", "abbreviation": "Gal", "testament": "NT", "chapters": 6},
    {"name": "Ephesians", "abbreviation": "Eph", "testament": "NT", "chapters": 6},
    {"name": "Philippians", "abbreviation": "Phil", "testament": "NT", "chapters": 4},
    {"name": "Colossians", "abbreviation": "Col", "testament": "NT", "chapters": 4},
    {"name": "1 Thessalonians", "abbreviation": "1Thess", "testament": "NT", "chapters": 5},
    {"name": "2 Thessalonians", "abbreviation": "2Thess", "testament": "NT", "chapters": 3},
    {"name": "1 Timothy", "abbreviation": "1Tim", "testament": "NT", "chapters": 6},
    {"name": "2 Timothy", "abbreviation": "2Tim", "testament": "NT", "chapters": 4},
    {"name": "Titus", "abbreviation": "Titus", "testament": "NT", "chapters": 3},
    {"name": "Philemon", "abbreviation": "Phlm", "testament": "NT", "chapters": 1},
    {"name": "Hebrews", "abbreviation": "Heb", "testament": "NT", "chapters": 13},
    {"name": "James", "abbreviation": "Jas", "testament": "NT", "chapters": 5},
    {"name": "1 Peter", "abbreviation": "1Pet", "testament": "NT", "chapters": 5},
    {"name": "2 Peter", "abbreviation": "2Pet", "testament": "NT", "chapters": 3},
    {"name": "1 John", "abbreviation": "1John", "testament": "NT", "chapters": 5},
    {"name": "2 John", "abbreviation": "2John", "testament": "NT", "chapters": 1},
    {"name": "3 John", "abbreviation": "3John", "testament": "NT", "chapters": 1},
    {"name": "Jude", "abbreviation": "Jude", "testament": "NT", "chapters": 1},
    {"name": "Revelation", "abbreviation": "Rev", "testament": "NT", "chapters": 22},
]
